"""initial

Revision ID: 6aa7f9343846
Revises: 
Create Date: 2024-06-19 23:31:40.045680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6aa7f9343846"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enemies",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("current_hp", sa.Integer(), nullable=False),
        sa.Column("gold_reward", sa.Integer(), nullable=False),
        sa.Column("is_dead", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enemies")),
        sa.UniqueConstraint("name", name=op.f("uq_enemies_name")),
    )
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "attack_power", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("gold", sa.Integer(), server_default="650", nullable=False),
        sa.Column(
            "max_energy", sa.Integer(), server_default="2000", nullable=False
        ),
        sa.Column(
            "current_energy",
            sa.Integer(),
            server_default="2000",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "users_enemy",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("enemy_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enemy_id"],
            ["enemies.id"],
            name=op.f("fk_users_enemy_enemy_id_enemies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_enemy_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "enemy_id", "id", name=op.f("pk_users_enemy")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_enemy")
    op.drop_table("users")
    op.drop_table("enemies")
    # ### end Alembic commands ###
