"""init

Revision ID: 54d0bf97c706
Revises: 
Create Date: 2024-06-16 18:29:33.966974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54d0bf97c706"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "attack_power", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("gold", sa.Integer(), server_default="650", nullable=False),
        sa.Column(
            "max_energy", sa.Integer(), server_default="2000", nullable=False
        ),
        sa.Column(
            "current_energy",
            sa.Integer(),
            server_default="2000",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "enemies",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("current_hp", sa.Integer(), nullable=False),
        sa.Column("gold_reward", sa.Integer(), nullable=False),
        sa.Column("is_dead", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_enemies_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enemies")),
        sa.UniqueConstraint("name", name=op.f("uq_enemies_name")),
        sa.UniqueConstraint("user_id", name=op.f("uq_enemies_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enemies")
    op.drop_table("users")
    # ### end Alembic commands ###
